project:
  type: book

book:
  title: "A Practical Guide to Ecosystem Forecasting"
  sidebar:
    search: true
    logo: img/VT-CEF.png
    url: https://frec-5174.github.io/eco4cast-in-R-book/
  repo-url: https://github.com/frec-5174/eco4cast-in-R-book
  repo-branch: main
  repo-actions: [issue, source]
  image: img/VT-CEF.jpg
  author:
    - name: "R. Quinn Thomas"
      orcid: 0000-0003-1282-7825
      email: rqthomas@vt.edu
      url: https://rquinnthomas.com
      affiliation:
        - Co-director of Virginia Tech Center for Ecosystem Forecasting
        - Departments of Forest Resources and Environmental Conservation and Biological Sciences
        - Virginia Tech
  date: today
  date-format: long
  license: "CC BY-NC-ND"
  chapters:
    - index.qmd
    - intro.qmd
    - background-skills.qmd
    - part: setting-the-stage.qmd
      chapters:
        - intro-ecoforecast.qmd
        - first-forecast.qmd
        - understand-uncertainty.qmd
        - second-forecast.qmd
        - using-data.qmd
        - third-forecast.qmd
        - decision-making.qmd
        - visualizing.qmd
        - best-practices.qmd
    - part: "Project 1"
      chapters:
        - project1.qmd
    - part: advanced-forecasting.qmd
      chapters:
        - process-model.qmd
        - prop-uncertainty.qmd
        - neon-data.qmd
        - likelihood-methods.qmd
        - bayesian-methods-intro.qmd
        - bayesian-process-models.qmd
        - particle-filter.qmd
        - particle-filter-process-model.qmd
        - process-model-forecast.qmd
        - process-model-forecast-evaluation.qmd
    - part: "Project 2"
      chapters:
        - project2.qmd
    - references.qmd
    - part: "Appendix"
      chapters:
      - weather-drivers.qmd
      - example-schedule.qmd
      - nimble.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

